global:
    TIME_ZONE: "Europe/Paris"

jwt:
    ALGORITHMS: "HS256"
    ACCESS_TOKEN_LIFETIME: 10 # in minutes, 10 min by default
    REFRESH_TOKEN_LIFETIME: 720 # in minutes, 720 min (12 hours) by default
